import { db } from "../lib/db";
import {
  ExperienceLevel,
  JobType,
  Role,
  Status,
  StatusTypes,
} from "@prisma/client";
import * as bcrypt from "bcryptjs";

async function main() {
  console.log("Seeding database...");

  await db.$transaction(async (tx) => {
    //deleting the fields first
    await tx.session.deleteMany({});
    await tx.account.deleteMany({});
    await tx.activityLog.deleteMany({});
    await tx.hire.deleteMany({});
    await tx.user.deleteMany({});
    await tx.category.deleteMany({});
    await tx.job.deleteMany({});
    await tx.application.deleteMany({});

    console.log("All Data deleted✅");
    // Hash passwords
    const userPasswordHash = await bcrypt.hash("User@2025", 10);
    const employerPasswordHash = await bcrypt.hash("Employer@2025", 10);
    const adminPasswordHash = await bcrypt.hash("Admin@2025", 10);

    const users = [
      {
        name: "John Doe",
        email: "user@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Frontend Developer",
        salary: 2900,
        emailVerified: null,
        headline: "Aspiring Frontend Developer",
        summary: "Passionate about building web applications.",
        skills: ["JavaScript", "React", "CSS"],
        city: "Kampala",
        state: "Central",
        country: "Uganda",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/johndoe",
        github: "https://github.com/johndoe",
        website: "https://johndoe.dev",
        image: "https://hrty.vercel.app/9jBsAb",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Jane Trust",
        email: "employer@gmail.com",
        passwordHash: employerPasswordHash,
        role: Role.EMPLOYER,
        job: "Hiring Manager",
        salary: 900,
        emailVerified: null,
        headline: "Hiring Manager at TechCorp",
        summary: "Looking to connect with skilled developers.",
        skills: [],
        city: "Nairobi",
        state: "Nairobi County",
        country: "Kenya",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/janetrust",
        github: null,
        website: "https://techcorp.com",
        image: "https://hrty.vercel.app/rlGLLg",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Admin User",
        email: "admin@gmail.com",
        passwordHash: adminPasswordHash,
        role: Role.ADMIN,
        job: "System Administrator",
        salary: 1900,
        emailVerified: null,
        headline: "System Administrator",
        summary: "Managing platform and user access.",
        skills: ["Node.js", "DevOps"],
        city: "Lagos",
        state: "Lagos State",
        country: "Nigeria",
        token: null,
        resume: null,
        linkedin: null,
        github: null,
        website: null,
        image: "hhttps://hrty.vercel.app/l7TIZP",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Angela Kyomugisha",
        email: "angela.kyomugisha@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Graphic Designer",
        salary: 100,
        emailVerified: null,
        headline: "Creative Visual Artist",
        summary: "Bringing ideas to life through design.",
        skills: ["Photoshop", "Illustrator", "Figma"],
        city: "Mbarara",
        state: "Western",
        country: "Uganda",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/angelak",
        github: null,
        website: null,
        image: "https://hrty.vercel.app/vbLNOy",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Brian Otieno",
        email: "brian.otieno@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Backend Developer",
        salary: 800,
        emailVerified: null,
        headline: "Node.js Enthusiast",
        summary: "Building reliable APIs and microservices.",
        skills: ["Node.js", "Express", "MongoDB"],
        city: "Kisumu",
        state: "Nyanza",
        country: "Kenya",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/brianotieno",
        github: "https://github.com/brianotieno",
        website: null,
        image: "https://hrty.vercel.app/wGwNE9",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Naomi Ninsiima",
        email: "naomi.ninsiima@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Product Manager",
        salary: 500,
        emailVerified: null,
        headline: "Delivering Product Value",
        summary: "Focused on user experience and product strategy.",
        skills: ["Product Management", "Scrum", "Analytics"],
        city: "Kampala",
        state: "Central",
        country: "Uganda",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/naomininsiima",
        github: null,
        website: null,
        image: "https://hrty.vercel.app/YikJoA",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Michael Karanja",
        email: "mkaranja@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "UI/UX Designer",
        salary: 290,
        emailVerified: null,
        headline: "Designing Interfaces That Work",
        summary: "Creating intuitive user experiences.",
        skills: ["Figma", "Sketch", "Wireframing"],
        city: "Nakuru",
        state: "Rift Valley",
        country: "Kenya",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/mkaranja",
        github: null,
        website: "https://karanja.design",
        image: "https://hrty.vercel.app/rCTFg2",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Aisha Namutebi",
        email: "aisha.namutebi@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Digital Marketer",
        salary: 60,
        emailVerified: null,
        headline: "Boosting Online Presence",
        summary: "Driving traffic and conversions through digital strategies.",
        skills: ["SEO", "Google Ads", "Social Media"],
        city: "Entebbe",
        state: "Central",
        country: "Uganda",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/aishanamutebi",
        github: null,
        website: null,
        image: "https://hrty.vercel.app/TfP5Pg",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "James Mwangi",
        email: "jamesmwangi@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Data Analyst",
        salary: 200,
        emailVerified: null,
        headline: "Making Data Make Sense",
        summary: "Transforming raw data into actionable insights.",
        skills: ["Python", "SQL", "Power BI"],
        city: "Nairobi",
        state: "Nairobi County",
        country: "Kenya",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/jmwangi",
        github: null,
        website: null,
        image: "https://hrty.vercel.app/evx-kK",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Esther Nakanwagi",
        email: "esthernakanwagi@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "QA Engineer",
        salary: 90,
        emailVerified: null,
        headline: "Quality First",
        summary: "Ensuring software quality and reliability.",
        skills: ["Test Automation", "Selenium", "Jest"],
        city: "Jinja",
        state: "Eastern",
        country: "Uganda",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/esthernakanwagi",
        github: null,
        website: null,
        image: "https://hrty.vercel.app/Kqm7Bo",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Kevin Barasa",
        email: "kevinbarasa@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "DevOps Engineer",
        salary: 100,
        emailVerified: null,
        headline: "Infrastructure & Automation",
        summary: "Automating deployment and scaling infrastructure.",
        skills: ["Docker", "Kubernetes", "CI/CD"],
        city: "Eldoret",
        state: "Rift Valley",
        country: "Kenya",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/kevinbarasa",
        github: "https://github.com/kevinbarasa",
        website: null,
        image: "https://hrty.vercel.app/zwQu9Z",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Linda Achieng",
        email: "linda.achieng@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Content Writer",
        salary: 30,
        emailVerified: null,
        headline: "Crafting Compelling Stories",
        summary: "Creating content that connects with audiences.",
        skills: ["Writing", "SEO", "Research"],
        city: "Kisumu",
        state: "Nyanza",
        country: "Kenya",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/lindaachieng",
        github: null,
        website: null,
        image: "https://hrty.vercel.app/B0b0vS",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "David Turyamureeba",
        email: "david.turyamureeba@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Mobile Developer",
        salary: 900,
        emailVerified: null,
        headline: "Android & iOS Specialist",
        summary: "Building mobile-first experiences.",
        skills: ["Flutter", "React Native", "Dart"],
        city: "Fort Portal",
        state: "Western",
        country: "Uganda",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/davidturyamureeba",
        github: "https://github.com/davidtury",
        website: null,
        image: "https://hrty.vercel.app/rzqHZB",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Grace Wanjiru",
        email: "grace.wanjiru@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "UI Designer",
        salary: 48,
        emailVerified: null,
        headline: "Design with Purpose",
        summary: "Creating beautiful and functional interfaces.",
        skills: ["Adobe XD", "Figma", "Prototyping"],
        city: "Thika",
        state: "Central",
        country: "Kenya",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/gracewanjiru",
        github: null,
        website: null,
        image: "https://hrty.vercel.app/eDeAcj",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Samuel Kaggwa",
        email: "samuel.kaggwa@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Full Stack Developer",
        salary: 500,
        emailVerified: null,
        headline: "From Front to Back",
        summary: "Coding across the stack with modern technologies.",
        skills: ["React", "Node.js", "PostgreSQL"],
        city: "Masaka",
        state: "Central",
        country: "Uganda",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/samuelkaggwa",
        github: "https://github.com/skaggwa",
        website: null,
        image: "https://hrty.vercel.app/n2L6eQ",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Catherine Njeri",
        email: "catherine.njeri@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Software Tester",
        salary: 70,
        emailVerified: null,
        headline: "Ensuring Software Integrity",
        summary: "Delivering bug-free experiences.",
        skills: ["Manual Testing", "Postman", "Jira"],
        city: "Naivasha",
        state: "Rift Valley",
        country: "Kenya",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/catherinenjeri",
        github: null,
        website: null,
        image: "https://hrty.vercel.app/MFZQjD",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Daniel Mugisha",
        email: "daniel.mugisha@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Cybersecurity Analyst",
        salary: 900,
        emailVerified: null,
        headline: "Defending Digital Assets",
        summary: "Protecting systems from threats.",
        skills: ["Network Security", "Penetration Testing", "Firewalls"],
        city: "Kampala",
        state: "Central",
        country: "Uganda",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/danielmugisha",
        github: null,
        website: null,
        image: "https://hrty.vercel.app/Ez3Wu1",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Beatrice Aoko",
        email: "beatrice.aoko@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Business Analyst",
        salary: 100,
        emailVerified: null,
        headline: "Turning Requirements into Reality",
        summary: "Linking business needs with technical solutions.",
        skills: ["Business Analysis", "UML", "Requirements Gathering"],
        city: "Mombasa",
        state: "Coast",
        country: "Kenya",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/beatriceaoko",
        github: null,
        website: null,
        image: "https://hrty.vercel.app/iiuP6w",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "John Tumwesigye",
        email: "john.tumwesigye@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Database Administrator",
        salary: 90,
        emailVerified: null,
        headline: "Guardian of Data",
        summary: "Ensuring data availability and performance.",
        skills: ["SQL", "Oracle", "Backup & Recovery"],
        city: "Mbale",
        state: "Eastern",
        country: "Uganda",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/johntumwesigye",
        github: null,
        website: null,
        image: "https://hrty.vercel.app/4Rj8W0",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Joyce Muthoni",
        email: "joyce.muthoni@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Marketing Strategist",
        salary: 80,
        emailVerified: null,
        headline: "Marketing with a Mission",
        summary: "Creating and executing impactful strategies.",
        skills: ["Market Research", "Email Campaigns", "Brand Strategy"],
        city: "Machakos",
        state: "Eastern",
        country: "Kenya",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/joycemuthoni",
        github: null,
        website: null,
        image: "https://hrty.vercel.app/bHvFwY",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
      {
        name: "Richard Okello",
        email: "richard.okello@gmail.com",
        passwordHash: userPasswordHash,
        role: Role.USER,
        job: "Technical Writer",
        salary: 25,
        emailVerified: null,
        headline: "Simplifying the Complex",
        summary: "Creating clear and concise documentation.",
        skills: ["Markdown", "API Docs", "Git"],
        city: "Gulu",
        state: "Northern",
        country: "Uganda",
        token: null,
        resume: null,
        linkedin: "https://linkedin.com/in/richardokello",
        github: null,
        website: null,
        image: "https://hrty.vercel.app/Rdjv_g",
        isMachine: false,
        invalidLoginAttempts: 0,
        lockedAt: null,
      },
    ];

    for (const user of users) {
      await tx.user.upsert({
        where: { email: user.email },
        update: {},
        create: user,
      });
    }
    console.log("users created: ✅");
    const jobCreator = await tx.user.findUnique({
      where: {
        email: "employer@gmail.com",
      },
    });
    if (!jobCreator) {
      console.log("User not available");
      return;
    }

    const categories = [
      {
        title: "Information Technology",
        slug: "information-technology",
      },
      {
        title: "Healthcare and Medical",
        slug: "healthcare-medical",
      },
      {
        title: "Finance and Accounting",
        slug: "finance-accounting",
      },
      {
        title: "Education and Training",
        slug: "education-training",
      },
      {
        title: "Marketing and Communications",
        slug: "marketing-communications",
      },
      {
        title: "Engineering",
        slug: "engineering",
      },
      {
        title: "Sales and Business Development",
        slug: "sales-business-development",
      },
      {
        title: "Customer Service",
        slug: "customer-service",
      },
      {
        title: "Human Resources",
        slug: "human-resources",
      },
      {
        title: "Logisticsa and Supply Chain",
        slug: "logistics-supply-chain",
      },
    ];

    for (const category of categories) {
      await tx.category.create({
        data: category,
      });
    }
    console.log("Categories created: ✅");
    const allCategories = await tx.category.findMany({});

    const jobs = [
      {
        title: "Software Engineer",
        description:
          "Google is seeking a talented Software Engineer to design and develop scalable software solutions that power our global services.",
        company: "Google",
        salary: 130000,
        isSaved: true,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        city: "Mountain View",
        country: "USA",
        categoryId: allCategories[0].id,
        status: StatusTypes.active,
        requiredSkills: ["Python", "C++", "Algorithms"],
        deadline: "2025-10-01T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Data Scientist",
        description:
          "Microsoft is looking for a Data Scientist to analyze large datasets, build predictive models, and drive data-informed decisions.",
        company: "Microsoft",
        salary: 125000,
        jobType: JobType.REMOTE,
        isSaved: true,
        experience: ExperienceLevel.mid,
        city: "Redmond",
        country: "USA",
        categoryId: allCategories[0].id,
        status: StatusTypes.active,
        requiredSkills: ["Python", "Machine Learning", "Statistics"],
        deadline: "2025-10-02T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Product Manager",
        description:
          "Amazon seeks an experienced Product Manager to lead product development, set strategic direction, and coordinate cross-functional teams.",
        company: "Amazon",
        salary: 140000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        city: "Seattle",
        isSaved: true,
        categoryId: allCategories[0].id,
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Product Strategy", "Communication", "Agile"],
        deadline: "2025-10-03T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Marketing Manager",
        description:
          "Facebook is hiring a Marketing Manager to drive brand awareness, lead digital campaigns, and analyze market trends.",
        company: "Facebook",
        salary: 115000,
        jobType: JobType.ONSITE,
        experience: ExperienceLevel.mid,
        city: "Menlo Park",
        country: "USA",
        status: StatusTypes.active,
        categoryId: allCategories[0].id,
        requiredSkills: ["Digital Marketing", "SEO", "Content Strategy"],
        deadline: "2025-10-04T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Sales Representative",
        description:
          "Apple is seeking a dynamic Sales Representative to drive sales growth, build lasting customer relationships, and represent our innovative products.",
        company: "Apple",
        salary: 110000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.entry,
        city: "Cupertino",
        country: "USA",
        categoryId: allCategories[0].id,
        status: StatusTypes.active,
        requiredSkills: ["Sales", "Customer Relationship", "Negotiation"],
        deadline: "2025-10-05T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Financial Analyst",
        description:
          "Goldman Sachs is looking for a Financial Analyst to develop financial models, perform market analysis, and support investment strategies.",
        company: "Goldman Sachs",
        salary: 120000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        categoryId: allCategories[1].id,
        requiredSkills: ["Financial Modeling", "Excel", "Analysis"],
        deadline: "2025-10-06T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Human Resources Specialist",
        description:
          "IBM is seeking an HR Specialist to support recruitment, employee engagement, and the implementation of HR policies.",
        company: "IBM",
        salary: 90000,
        jobType: JobType.ONSITE,
        experience: ExperienceLevel.entry,
        categoryId: allCategories[1].id,
        city: "Armonk",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["HR Policies", "Recruitment", "Employee Relations"],
        deadline: "2025-10-07T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Graphic Designer",
        description:
          "Adobe is seeking a creative Graphic Designer to produce visually compelling designs for digital and print media.",
        company: "Adobe",
        salary: 95000,
        jobType: JobType.REMOTE,
        categoryId: allCategories[1].id,
        experience: ExperienceLevel.mid,
        city: "San Jose",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Adobe Creative Suite", "Illustration", "Branding"],
        deadline: "2025-10-08T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Systems Administrator",
        categoryId: allCategories[1].id,
        description:
          "Cisco is looking for a Systems Administrator to manage, secure, and optimize network infrastructure across our global operations.",
        company: "Cisco",
        salary: 105000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        city: "San Jose",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Networking", "Linux", "System Monitoring"],
        deadline: "2025-10-09T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "IT Support Specialist",
        description:
          "Dell is hiring an IT Support Specialist to troubleshoot technical issues, assist customers, and ensure smooth IT operations.",
        company: "Dell",
        salary: 80000,
        jobType: JobType.FULLTIME,
        categoryId: allCategories[1].id,
        experience: ExperienceLevel.entry,
        city: "Round Rock",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Technical Support",
          "Troubleshooting",
          "Customer Service",
        ],
        deadline: "2025-10-10T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "DevOps Engineer",
        description:
          "Netflix is seeking a DevOps Engineer to implement continuous integration, manage cloud infrastructure, and improve deployment processes.",
        company: "Netflix",
        salary: 135000,
        jobType: JobType.FULLTIME,
        categoryId: allCategories[2].id,
        experience: ExperienceLevel.senior,
        city: "Los Gatos",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Docker", "Kubernetes", "CI/CD"],
        deadline: "2025-10-11T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Cybersecurity Analyst",
        description:
          "Palo Alto Networks seeks a Cybersecurity Analyst to protect digital assets through threat analysis, monitoring, and incident response.",
        company: "Palo Alto Networks",
        salary: 125000,
        jobType: JobType.ONSITE,
        categoryId: allCategories[2].id,
        experience: ExperienceLevel.mid,
        city: "Santa Clara",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Security", "Incident Response", "Risk Assessment"],
        deadline: "2025-10-12T00:00:00.000Z",
        userId: jobCreator.id,
        isSaved: true,
      },
      {
        title: "Business Analyst",
        description:
          "Accenture is looking for a Business Analyst to drive process improvements, analyze business needs, and deliver actionable insights.",
        company: "Accenture",
        salary: 100000,
        jobType: JobType.FULLTIME,
        categoryId: allCategories[2].id,
        experience: ExperienceLevel.entry,
        city: "Chicago",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Data Analysis",
          "Process Improvement",
          "Stakeholder Management",
        ],
        deadline: "2025-10-13T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Project Manager",
        description:
          "Oracle seeks a Project Manager to lead cross-functional teams, manage project lifecycles, and ensure timely delivery of technical projects.",
        company: "Oracle",
        salary: 130000,
        jobType: JobType.FULLTIME,
        categoryId: allCategories[2].id,
        experience: ExperienceLevel.senior,
        city: "Redwood City",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Project Management", "Agile", "Risk Management"],
        deadline: "2025-10-14T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Mobile Developer",
        description:
          "Uber is hiring a Mobile Developer to build intuitive iOS and Android applications that enhance the ride-sharing experience.",
        company: "Uber",
        salary: 125000,
        jobType: JobType.FULLTIME,
        categoryId: allCategories[3].id,
        experience: ExperienceLevel.mid,
        city: "San Francisco",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["iOS", "Android", "React Native"],
        deadline: "2025-10-15T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "UX/UI Designer",
        description:
          "Airbnb is seeking a UX/UI Designer to create seamless user interfaces and engaging user experiences for our hospitality platform.",
        company: "Airbnb",
        categoryId: allCategories[3].id,
        salary: 115000,
        jobType: JobType.REMOTE,
        experience: ExperienceLevel.mid,
        city: "San Francisco",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["UX Research", "UI Design", "Prototyping"],
        deadline: "2025-10-16T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Cloud Architect",
        description:
          "AWS seeks a Cloud Architect to design, implement, and manage scalable cloud infrastructures for our enterprise clients.",
        company: "AWS",
        salary: 150000,
        categoryId: allCategories[3].id,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        city: "Seattle",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Cloud Computing", "AWS", "Architecture"],
        deadline: "2025-10-17T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Machine Learning Engineer",
        description:
          "Tesla is hiring a Machine Learning Engineer to develop advanced algorithms for autonomous driving and smart vehicle systems.",
        company: "Tesla",
        salary: 145000,
        categoryId: allCategories[3].id,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        city: "Palo Alto",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Machine Learning", "Deep Learning", "Python"],
        deadline: "2025-10-18T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Quality Assurance Engineer",
        description:
          "Intel requires a Quality Assurance Engineer to implement test plans, automate testing processes, and ensure high-quality product releases.",
        company: "Intel",
        salary: 110000,
        categoryId: allCategories[3].id,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        city: "Santa Clara",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Testing", "Automation", "Scripting"],
        deadline: "2025-10-19T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Full Stack Developer",
        description:
          "Salesforce seeks a Full Stack Developer to build robust web applications that power our customer relationship management tools.",
        company: "Salesforce",
        salary: 135000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[4].id,
        city: "San Francisco",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["JavaScript", "Node.js", "React"],
        deadline: "2025-10-20T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Database Administrator",
        description:
          "SAP is looking for a Database Administrator to manage, secure, and optimize our enterprise-level databases.",
        company: "SAP",
        salary: 120000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[4].id,
        city: "Walldorf",
        country: "Germany",
        status: StatusTypes.active,
        requiredSkills: ["SQL", "Database Management", "Performance Tuning"],
        deadline: "2025-10-21T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Network Engineer",
        description:
          "Verizon seeks a Network Engineer to design, implement, and maintain robust communications networks across our service regions.",
        company: "Verizon",
        salary: 105000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[4].id,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Networking", "Routing", "Switching"],
        deadline: "2025-10-22T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Software Architect",
        description:
          "Twitter is hiring a Software Architect to define system architecture, lead technical teams, and drive our engineering vision.",
        company: "Twitter",
        salary: 150000,
        jobType: JobType.FULLTIME,
        isSaved: true,
        experience: ExperienceLevel.executive,
        categoryId: allCategories[4].id,
        city: "San Francisco",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Architecture", "Microservices", "Leadership"],
        deadline: "2025-10-23T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Digital Marketing Specialist",
        description:
          "LinkedIn seeks a Digital Marketing Specialist to enhance our online presence through strategic content and social media campaigns.",
        company: "LinkedIn",
        salary: 95000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[4].id,
        city: "Sunnyvale",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Digital Marketing",
          "Social Media",
          "Content Creation",
        ],
        deadline: "2025-10-24T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Operations Manager",
        description:
          "Walmart is seeking an Operations Manager to streamline store operations, optimize supply chains, and drive team performance.",
        company: "Walmart",
        salary: 100000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        city: "Bentonville",
        country: "USA",
        categoryId: allCategories[4].id,
        status: StatusTypes.active,
        requiredSkills: [
          "Operations Management",
          "Logistics",
          "Team Leadership",
        ],
        deadline: "2025-10-25T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Research Scientist",
        description:
          "IBM Research is hiring a Research Scientist to drive breakthrough innovations and advance our technology portfolio.",
        company: "IBM Research",
        salary: 140000,
        jobType: JobType.FULLTIME,
        categoryId: allCategories[5].id,
        experience: ExperienceLevel.executive,
        city: "Yorktown Heights",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Research", "Innovation", "Data Analysis"],
        deadline: "2025-10-26T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Mechanical Engineer",
        description:
          "Ford seeks a Mechanical Engineer to design and optimize automotive components, ensuring performance and safety.",
        company: "Ford",
        salary: 95000,
        jobType: JobType.FULLTIME,
        isSaved: true,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[5].id,
        city: "Detroit",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["CAD", "Mechanical Design", "Manufacturing"],
        deadline: "2025-10-27T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Electrical Engineer",
        description:
          "GE is looking for an Electrical Engineer to design, test, and maintain electrical systems for industrial and consumer products.",
        company: "GE",
        salary: 100000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[5].id,
        city: "Boston",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Circuit Design", "Electronics", "Troubleshooting"],
        deadline: "2025-10-28T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Civil Engineer",
        description:
          "Bechtel requires a Civil Engineer to oversee the design and construction of infrastructure projects from conception to completion.",
        company: "Bechtel",
        salary: 105000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[5].id,
        city: "San Francisco",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Structural Analysis",
          "Project Management",
          "AutoCAD",
        ],
        deadline: "2025-10-29T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Data Engineer",
        description:
          "Cloudera seeks a Data Engineer to develop, construct, and maintain large-scale data processing systems and pipelines.",
        company: "Cloudera",
        salary: 115000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[5].id,
        city: "Palo Alto",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Big Data", "ETL", "SQL"],
        deadline: "2025-10-30T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Blockchain Developer",
        description:
          "ConsenSys is hiring a Blockchain Developer to create decentralized applications and smart contracts on the Ethereum platform.",
        company: "ConsenSys",
        salary: 130000,
        jobType: JobType.REMOTE,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[5].id,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Blockchain", "Ethereum", "Smart Contracts"],
        deadline: "2025-10-31T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Technical Writer",
        description:
          "Red Hat seeks a Technical Writer to develop clear, concise documentation that helps users understand our open source software solutions.",
        company: "Red Hat",
        salary: 85000,
        jobType: JobType.FULLTIME,
        categoryId: allCategories[6].id,
        experience: ExperienceLevel.mid,
        city: "Raleigh",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Writing", "Technical Documentation", "Linux"],
        deadline: "2025-11-01T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "SEO Specialist",
        description:
          "Moz is looking for an SEO Specialist to optimize search engine rankings and boost organic traffic through data-driven strategies.",
        company: "Moz",
        salary: 80000,
        categoryId: allCategories[6].id,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.entry,
        city: "Seattle",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["SEO", "Google Analytics", "Content Strategy"],
        deadline: "2025-11-02T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Content Strategist",
        description:
          "HubSpot seeks a Content Strategist to develop engaging content and drive inbound marketing campaigns that resonate with our audience.",
        company: "HubSpot",
        salary: 90000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[6].id,
        city: "Cambridge",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Content Creation", "Strategy", "SEO"],
        deadline: "2025-11-03T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Social Media Manager",
        description:
          "Hootsuite is hiring a Social Media Manager to drive engagement, manage campaigns, and analyze performance across multiple platforms.",
        company: "Hootsuite",
        salary: 85000,
        jobType: JobType.REMOTE,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[6].id,
        city: "Vancouver",
        country: "Canada",
        status: StatusTypes.active,
        requiredSkills: ["Social Media", "Content Creation", "Analytics"],
        deadline: "2025-11-04T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "E-commerce Manager",
        description:
          "Shopify seeks an E-commerce Manager to optimize our online sales strategy, enhance customer experience, and drive revenue growth.",
        company: "Shopify",
        salary: 105000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[6].id,
        city: "Ottawa",
        country: "Canada",
        status: StatusTypes.active,
        requiredSkills: ["E-commerce", "Digital Marketing", "Analytics"],
        deadline: "2025-11-05T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Customer Success Manager",
        description:
          "Zendesk is seeking a Customer Success Manager to drive customer engagement, improve retention, and ensure clients achieve their business goals.",
        company: "Zendesk",
        salary: 95000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        city: "San Francisco",
        country: "USA",
        status: StatusTypes.active,
        categoryId: allCategories[6].id,
        requiredSkills: ["Customer Service", "CRM", "Relationship Building"],
        deadline: "2025-11-06T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Supply Chain Analyst",
        description:
          "UPS seeks a Supply Chain Analyst to optimize logistics operations, analyze supply chain data, and improve distribution efficiency.",
        company: "UPS",
        salary: 90000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.entry,
        categoryId: allCategories[7].id,
        city: "Atlanta",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Supply Chain", "Data Analysis", "Logistics"],
        deadline: "2025-11-07T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Logistics Coordinator",
        description:
          "FedEx is hiring a Logistics Coordinator to manage shipping schedules, coordinate deliveries, and ensure timely logistics operations.",
        company: "FedEx",
        salary: 85000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.entry,
        categoryId: allCategories[7].id,
        city: "Memphis",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Logistics", "Coordination", "Time Management"],
        deadline: "2025-11-08T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "UX Researcher",
        description:
          "IDEO seeks a UX Researcher to conduct user interviews, gather insights, and improve the overall user experience of our design projects.",
        company: "IDEO",
        salary: 95000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[7].id,
        city: "Palo Alto",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["UX Research", "User Interviews", "Data Analysis"],
        deadline: "2025-11-09T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Frontend Developer",
        description:
          "Spotify is hiring a Frontend Developer to build and enhance our web applications with modern JavaScript frameworks and responsive design.",
        company: "Spotify",
        salary: 120000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[7].id,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["React", "JavaScript", "CSS"],
        deadline: "2025-11-10T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Backend Developer",
        description:
          "Square seeks a Backend Developer to build robust server-side applications and APIs using modern frameworks and technologies.",
        company: "Square",
        salary: 125000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[7].id,
        city: "San Francisco",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Node.js", "Databases", "APIs"],
        deadline: "2025-11-11T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "AI Researcher",
        description:
          "OpenAI is hiring an AI Researcher to push the boundaries of artificial intelligence, developing cutting-edge deep learning models and algorithms.",
        company: "OpenAI",
        salary: 160000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.executive,
        categoryId: allCategories[7].id,
        city: "San Francisco",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Artificial Intelligence",
          "Deep Learning",
          "Research",
        ],
        deadline: "2025-11-12T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Game Developer",
        description:
          "Electronic Arts seeks a Game Developer to create immersive gaming experiences and innovative gameplay mechanics.",
        company: "Electronic Arts",
        salary: 115000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[8].id,
        city: "Redwood City",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["C++", "Game Design", "Unity"],
        deadline: "2025-11-13T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Embedded Systems Engineer",
        description:
          "ARM is looking for an Embedded Systems Engineer to develop innovative microcontroller solutions for next-generation devices.",
        company: "ARM",
        salary: 110000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[8].id,
        city: "Cambridge",
        country: "UK",
        status: StatusTypes.active,
        requiredSkills: ["Embedded Systems", "C", "Hardware"],
        deadline: "2025-11-14T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Robotics Engineer",
        description:
          "Boston Dynamics seeks a Robotics Engineer to design and build advanced robotic systems and automate complex tasks.",
        company: "Boston Dynamics",
        salary: 135000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[8].id,
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Robotics", "Control Systems", "C++"],
        deadline: "2025-11-15T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Data Analyst",
        description:
          "Nielsen is hiring a Data Analyst to interpret consumer data and generate insights that drive strategic decisions.",
        company: "Nielsen",
        salary: 85000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.entry,
        categoryId: allCategories[8].id,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Data Analysis", "Excel", "SQL"],
        deadline: "2025-11-16T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Marketing Coordinator",
        description:
          "PepsiCo seeks a Marketing Coordinator to support campaign planning, coordinate events, and execute market research projects.",
        company: "PepsiCo",
        salary: 75000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.entry,
        categoryId: allCategories[8].id,
        city: "Purchase",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Marketing", "Coordination", "Communication"],
        deadline: "2025-11-17T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Sales Manager",
        description:
          "Coca-Cola is looking for a Sales Manager to lead our sales team, develop strategic initiatives, and drive revenue growth.",
        company: "Coca-Cola",
        salary: 105000,
        jobType: JobType.FULLTIME,
        categoryId: allCategories[9].id,
        experience: ExperienceLevel.senior,
        city: "Atlanta",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Sales Leadership", "Strategy", "Customer Relations"],
        deadline: "2025-11-18T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Account Executive",
        description:
          "Salesforce seeks an Account Executive to manage client portfolios, generate new business, and maintain long-term relationships.",
        company: "Salesforce",
        salary: 110000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[9].id,
        city: "San Francisco",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Salesforce", "CRM", "Negotiation"],
        deadline: "2025-11-19T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Operations Analyst",
        description:
          "McKinsey & Company is hiring an Operations Analyst to identify process improvements and optimize business operations for our clients.",
        company: "McKinsey & Company",
        salary: 100000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[9].id,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Operations", "Analysis", "Problem Solving"],
        deadline: "2025-11-20T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Strategic Planner",
        description:
          "Deloitte seeks a Strategic Planner to analyze market trends, develop growth strategies, and support business transformation initiatives.",
        company: "Deloitte",
        salary: 115000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[9].id,
        city: "Chicago",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Strategy", "Market Analysis", "Consulting"],
        deadline: "2025-11-21T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Business Development Manager",
        description:
          "Cisco is hiring a Business Development Manager to drive new partnerships and identify growth opportunities in emerging markets.",
        company: "Cisco",
        salary: 120000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[9].id,
        city: "San Jose",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Business Development", "Networking", "Sales"],
        deadline: "2025-11-22T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Procurement Specialist",
        description:
          "Amazon seeks a Procurement Specialist to manage vendor contracts, negotiate pricing, and ensure efficient supply chain operations.",
        company: "Amazon",
        salary: 95000,
        jobType: JobType.FULLTIME,
        categoryId: allCategories[0].id,
        experience: ExperienceLevel.mid,
        city: "Seattle",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Procurement", "Negotiation", "Supply Chain"],
        deadline: "2025-11-23T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "IT Manager",
        description:
          "HP is looking for an IT Manager to oversee our technology infrastructure, lead IT teams, and ensure seamless IT operations.",
        company: "HP",
        salary: 115000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[1].id,
        city: "Palo Alto",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["IT Management", "Leadership", "Infrastructure"],
        deadline: "2025-11-24T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Customer Service Representative",
        description:
          "Comcast is hiring a Customer Service Representative to provide prompt assistance to clients and troubleshoot technical issues.",
        company: "Comcast",
        salary: 50000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.entry,
        categoryId: allCategories[2].id,
        city: "Philadelphia",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Customer Service",
          "Communication",
          "Problem Solving",
        ],
        deadline: "2025-11-25T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Public Relations Specialist",
        description:
          "Edelman seeks a Public Relations Specialist to manage media campaigns, enhance public image, and coordinate PR activities.",
        company: "Edelman",
        salary: 85000,
        categoryId: allCategories[3].id,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["PR", "Media Relations", "Communication"],
        deadline: "2025-11-26T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Event Coordinator",
        description:
          "Marriott is hiring an Event Coordinator to plan and execute corporate and social events while ensuring seamless event operations.",
        company: "Marriott",
        salary: 70000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.entry,
        categoryId: allCategories[4].id,
        city: "Bethesda",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Event Planning", "Coordination", "Communication"],
        deadline: "2025-11-27T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Risk Analyst",
        description:
          "Morgan Stanley seeks a Risk Analyst to assess financial risks, develop risk mitigation strategies, and support investment decisions.",
        company: "Morgan Stanley",
        salary: 110000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[5].id,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Risk Management", "Analysis", "Financial Modeling"],
        deadline: "2025-11-28T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Investment Banker",
        description:
          "JPMorgan Chase seeks an Investment Banker to lead large-scale financial transactions, provide strategic advice, and support corporate finance activities.",
        company: "JPMorgan Chase",
        salary: 150000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.executive,
        categoryId: allCategories[6].id,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Investment Banking",
          "Financial Analysis",
          "Negotiation",
        ],
        deadline: "2025-11-29T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Legal Counsel",
        description:
          "Baker McKenzie is hiring a Legal Counsel to provide expert legal guidance, manage contracts, and ensure regulatory compliance.",
        company: "Baker McKenzie",
        salary: 160000,
        jobType: JobType.FULLTIME,
        categoryId: allCategories[7].id,
        experience: ExperienceLevel.executive,
        city: "Chicago",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Legal", "Contract Negotiation", "Compliance"],
        deadline: "2025-11-30T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Policy Advisor",
        description:
          "The United Nations seeks a Policy Advisor to develop global policy initiatives, analyze international trends, and provide strategic recommendations.",
        company: "United Nations",
        salary: 140000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[8].id,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Policy Analysis",
          "International Relations",
          "Diplomacy",
        ],
        deadline: "2025-12-01T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Environmental Engineer",
        description:
          "EPA is looking for an Environmental Engineer to monitor environmental quality, enforce regulations, and develop sustainability projects.",
        company: "EPA",
        salary: 90000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[9].id,
        city: "Washington, D.C.",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Environmental Engineering",
          "Regulatory Compliance",
          "Sustainability",
        ],
        deadline: "2025-12-02T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Urban Planner",
        description:
          "AECOM seeks an Urban Planner to design and implement innovative urban development projects that enhance community living.",
        company: "AECOM",
        salary: 95000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[0].id,
        city: "Los Angeles",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Urban Planning", "GIS", "Project Management"],
        deadline: "2025-12-03T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Healthcare Administrator",
        description:
          "Kaiser Permanente is hiring a Healthcare Administrator to manage hospital operations, ensure regulatory compliance, and improve patient care.",
        company: "Kaiser Permanente",
        salary: 105000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[1].id,
        city: "Oakland",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Healthcare Management", "Operations", "Compliance"],
        deadline: "2025-12-04T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Clinical Research Coordinator",
        description:
          "Pfizer seeks a Clinical Research Coordinator to manage clinical trials, ensure regulatory adherence, and support study protocols.",
        company: "Pfizer",
        salary: 85000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.entry,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        categoryId: allCategories[2].id,
        requiredSkills: ["Clinical Research", "Regulatory", "Data Collection"],
        deadline: "2025-12-05T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Pharmacist",
        description:
          "CVS Health is looking for a Pharmacist to dispense medications, counsel patients, and ensure the safe use of pharmaceutical products.",
        company: "CVS Health",
        salary: 115000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[3].id,
        city: "Woonsocket",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Pharmacy",
          "Medication Management",
          "Patient Counseling",
        ],
        deadline: "2025-12-06T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Registered Nurse",
        description:
          "Mayo Clinic seeks a Registered Nurse to deliver high-quality patient care, collaborate with healthcare teams, and ensure clinical excellence.",
        company: "Mayo Clinic",
        salary: 95000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[3].id,
        city: "Rochester",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Nursing", "Patient Care", "Clinical Skills"],
        deadline: "2025-12-07T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Physician Assistant",
        description:
          "Cleveland Clinic is hiring a Physician Assistant to support physicians in patient care, perform clinical procedures, and manage treatment plans.",
        company: "Cleveland Clinic",
        salary: 105000,
        jobType: JobType.FULLTIME,
        categoryId: allCategories[4].id,
        experience: ExperienceLevel.mid,
        city: "Cleveland",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Physician Assistant",
          "Clinical Care",
          "Patient Management",
        ],
        deadline: "2025-12-08T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Medical Laboratory Technician",
        description:
          "Quest Diagnostics seeks a Medical Laboratory Technician to conduct diagnostic tests, process samples, and ensure accuracy in laboratory results.",
        company: "Quest Diagnostics",
        salary: 70000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.entry,
        categoryId: allCategories[4].id,
        city: "Secaucus",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Lab Techniques",
          "Sample Analysis",
          "Quality Control",
        ],
        deadline: "2025-12-09T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Biotech Researcher",
        description:
          "Genentech is hiring a Biotech Researcher to drive drug development and innovation through rigorous scientific research and experimentation.",
        company: "Genentech",
        salary: 130000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        city: "South San Francisco",
        categoryId: allCategories[5].id,
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Biotechnology", "Research", "Data Analysis"],
        deadline: "2025-12-10T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Biomedical Engineer",
        description:
          "Medtronic seeks a Biomedical Engineer to design, test, and improve medical devices that enhance patient care and treatment outcomes.",
        company: "Medtronic",
        salary: 115000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[5].id,
        city: "Minneapolis",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Biomedical Engineering",
          "Product Development",
          "Regulatory Compliance",
        ],
        deadline: "2025-12-11T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Nutritionist",
        description:
          "Whole Foods is seeking a Nutritionist to provide dietary guidance, develop meal plans, and support wellness initiatives for our customers.",
        company: "Whole Foods",
        salary: 75000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.entry,
        categoryId: allCategories[6].id,
        city: "Austin",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Nutrition", "Diet Planning", "Client Counseling"],
        deadline: "2025-12-12T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Sports Marketing Manager",
        description:
          "Nike seeks a Sports Marketing Manager to develop creative marketing strategies, manage sponsorships, and elevate our brand in the athletic space.",
        company: "Nike",
        salary: 110000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[7].id,
        city: "Beaverton",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Sports Marketing",
          "Brand Management",
          "Campaign Strategy",
        ],
        deadline: "2025-12-13T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Brand Manager",
        description:
          "Adidas is hiring a Brand Manager to strengthen our brand identity, plan marketing initiatives, and drive consumer engagement.",
        company: "Adidas",
        salary: 105000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[8].id,
        city: "Portland",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Brand Strategy", "Marketing", "Creative Direction"],
        deadline: "2025-12-14T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Fashion Designer",
        description:
          "Levi's seeks a Fashion Designer to create innovative apparel designs, forecast trends, and contribute to our iconic brand legacy.",
        company: "Levi's",
        salary: 95000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        city: "San Francisco",
        categoryId: allCategories[9].id,
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Fashion Design", "Trend Analysis", "Creativity"],
        deadline: "2025-12-15T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Retail Manager",
        description:
          "Target is hiring a Retail Manager to oversee store operations, manage staff, and drive customer satisfaction in a fast-paced retail environment.",
        company: "Target",
        salary: 85000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[0].id,
        city: "Minneapolis",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Retail Management",
          "Customer Service",
          "Team Leadership",
        ],
        deadline: "2025-12-16T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Real Estate Agent",
        description:
          "Century 21 seeks a Real Estate Agent to help clients buy and sell properties, negotiate deals, and navigate the housing market.",
        company: "Century 21",
        salary: 80000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.entry,
        categoryId: allCategories[1].id,
        city: "Los Angeles",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Real Estate", "Sales", "Negotiation"],
        deadline: "2025-12-17T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Construction Project Manager",
        description:
          "Turner Construction is hiring a Construction Project Manager to oversee large-scale projects, manage budgets, and ensure safety compliance.",
        company: "Turner Construction",
        salary: 120000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[2].id,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Project Management", "Construction", "Budgeting"],
        deadline: "2025-12-18T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Architect",
        description:
          "Gensler seeks an Architect to design innovative building solutions and contribute to high-profile projects in the urban landscape.",
        company: "Gensler",
        salary: 115000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[3].id,
        city: "Los Angeles",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Architecture", "Design", "AutoCAD"],
        deadline: "2025-12-19T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Interior Designer",
        description:
          "IKEA is looking for an Interior Designer to create functional and appealing interior spaces that blend style with practicality.",
        company: "IKEA",
        salary: 90000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[4].id,
        city: "Delft",
        country: "Netherlands",
        status: StatusTypes.active,
        requiredSkills: ["Interior Design", "Creativity", "Space Planning"],
        deadline: "2025-12-20T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Customer Experience Manager",
        description:
          "American Express seeks a Customer Experience Manager to enhance service quality, streamline processes, and ensure exceptional client satisfaction.",
        company: "American Express",
        salary: 105000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        categoryId: allCategories[5].id,
        requiredSkills: [
          "Customer Experience",
          "Service Excellence",
          "Strategy",
        ],
        deadline: "2025-12-21T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Data Privacy Officer",
        description:
          "Facebook is hiring a Data Privacy Officer to oversee data protection initiatives, enforce privacy policies, and ensure regulatory compliance.",
        company: "Facebook",
        salary: 140000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.executive,
        categoryId: allCategories[5].id,
        city: "Menlo Park",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Data Privacy", "Compliance", "Policy"],
        deadline: "2025-12-22T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Compliance Officer",
        description:
          "Bank of America seeks a Compliance Officer to monitor regulatory changes, implement risk controls, and ensure adherence to industry standards.",
        company: "Bank of America",
        salary: 110000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[6].id,
        city: "Charlotte",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Compliance", "Risk Management", "Regulatory"],
        deadline: "2025-12-23T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Security Consultant",
        description:
          "KPMG is hiring a Security Consultant to advise clients on cybersecurity strategies, conduct risk assessments, and implement robust security measures.",
        company: "KPMG",
        salary: 125000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[6].id,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Security", "Consulting", "Risk Assessment"],
        deadline: "2025-12-24T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Quality Control Manager",
        description:
          "3M seeks a Quality Control Manager to oversee production processes, enforce quality standards, and drive continuous improvement in manufacturing.",
        company: "3M",
        salary: 95000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[7].id,
        city: "St. Paul",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Quality Control",
          "Inspection",
          "Process Improvement",
        ],
        deadline: "2025-12-25T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Production Supervisor",
        description:
          "General Motors is hiring a Production Supervisor to manage manufacturing operations, coordinate teams, and ensure high production standards.",
        company: "General Motors",
        salary: 105000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[8].id,
        city: "Detroit",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Production", "Team Leadership", "Operations"],
        deadline: "2025-12-26T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Process Engineer",
        description:
          "Honeywell seeks a Process Engineer to optimize manufacturing workflows, reduce waste, and improve product quality using lean methodologies.",
        company: "Honeywell",
        salary: 100000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[9].id,
        city: "Morris",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: [
          "Process Engineering",
          "Optimization",
          "Lean Manufacturing",
        ],
        deadline: "2025-12-27T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Safety Engineer",
        description:
          "DuPont is looking for a Safety Engineer to assess workplace risks, implement safety protocols, and ensure regulatory compliance in production facilities.",
        company: "DuPont",
        salary: 95000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[0].id,
        city: "Wilmington",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Safety", "Risk Assessment", "Regulations"],
        deadline: "2025-12-28T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "R&D Manager",
        description:
          "Johnson & Johnson seeks an R&D Manager to lead research initiatives, drive innovation, and oversee the development of new products.",
        company: "Johnson & Johnson",
        salary: 135000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.executive,
        categoryId: allCategories[1].id,
        city: "New Brunswick",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["R&D", "Innovation", "Team Management"],
        deadline: "2025-12-29T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Supply Chain Manager",
        description:
          "Procter & Gamble is hiring a Supply Chain Manager to optimize global supply operations, manage logistics, and reduce operational costs.",
        company: "Procter & Gamble",
        salary: 115000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[2].id,
        city: "Cincinnati",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Supply Chain", "Logistics", "Operations"],
        deadline: "2025-12-30T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Logistics Manager",
        description:
          "DHL seeks a Logistics Manager to oversee international shipping, manage distribution networks, and coordinate cross-border operations.",
        company: "DHL",
        salary: 110000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[3].id,
        city: "Bonn",
        country: "Germany",
        status: StatusTypes.active,
        requiredSkills: ["Logistics", "Operations", "Team Leadership"],
        deadline: "2025-12-31T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "International Trade Specialist",
        description:
          "Maersk is hiring an International Trade Specialist to manage global trade operations, ensure regulatory compliance, and optimize logistics processes.",
        company: "Maersk",
        salary: 105000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[4].id,
        city: "Copenhagen",
        country: "Denmark",
        status: StatusTypes.active,
        requiredSkills: [
          "International Trade",
          "Logistics",
          "Regulatory Compliance",
        ],
        deadline: "2026-01-01T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Economist",
        description:
          "The World Bank seeks an Economist to conduct economic research, analyze global market trends, and provide policy recommendations for sustainable growth.",
        company: "World Bank",
        salary: 140000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.executive,
        categoryId: allCategories[5].id,
        city: "Washington, D.C.",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Economics", "Data Analysis", "Policy"],
        deadline: "2026-01-02T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Statistician",
        description:
          "The Bureau of Labor Statistics is hiring a Statistician to analyze labor market data, forecast trends, and support policy formulation with rigorous analysis.",
        company: "Bureau of Labor Statistics",
        salary: 95000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[5].id,
        city: "Washington, D.C.",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Statistics", "Data Analysis", "Excel"],
        deadline: "2026-01-03T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Curriculum Developer",
        description:
          "Pearson seeks a Curriculum Developer to design engaging educational programs and develop high-quality learning materials for diverse audiences.",
        company: "Pearson",
        salary: 85000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[6].id,
        city: "London",
        country: "UK",
        status: StatusTypes.active,
        requiredSkills: [
          "Curriculum Design",
          "Education",
          "Content Development",
        ],
        deadline: "2026-01-04T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Educational Consultant",
        description:
          "Kaplan is hiring an Educational Consultant to advise on academic programs, develop student success strategies, and support curriculum improvements.",
        company: "Kaplan",
        salary: 90000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.mid,
        categoryId: allCategories[7].id,
        city: "Fort Lauderdale",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Education", "Consulting", "Strategy"],
        deadline: "2026-01-05T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Academic Advisor",
        description:
          "Harvard University seeks an Academic Advisor to guide students through their academic journey, providing support and counseling for success.",
        company: "Harvard University",
        salary: 75000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.entry,
        categoryId: allCategories[8].id,
        city: "Cambridge",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Academic Advising", "Student Support", "Counseling"],
        deadline: "2026-01-06T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Librarian",
        description:
          "The New York Public Library is hiring a Librarian to manage collections, assist patrons, and contribute to community educational programs.",
        company: "New York Public Library",
        salary: 65000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.entry,
        categoryId: allCategories[9].id,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Library Science", "Research", "Cataloging"],
        deadline: "2026-01-07T00:00:00.000Z",
        userId: jobCreator.id,
      },
      {
        title: "Museum Curator",
        description:
          "The Metropolitan Museum of Art seeks a Museum Curator to manage art collections, organize exhibitions, and contribute to cultural preservation.",
        company: "The Metropolitan Museum of Art",
        salary: 95000,
        jobType: JobType.FULLTIME,
        experience: ExperienceLevel.senior,
        categoryId: allCategories[0].id,
        city: "New York",
        country: "USA",
        status: StatusTypes.active,
        requiredSkills: ["Curation", "Art History", "Exhibition Design"],
        deadline: "2026-01-08T00:00:00.000Z",
        userId: jobCreator.id,
      },
    ];

    for (const job of jobs) {
      await tx.job.create({
        data: job,
      });
    }
    console.log("jobs created: ✅");
    const allJobs = await tx.job.findMany({});
    const normalUser = await tx.user.findUnique({
      where: {
        email: "user@gmail.com",
      },
    });

    if (!normalUser) {
      console.log("Normal user not found");
      return;
    }

    const applications = [
      {
        jobId: allJobs[0].id, // Full Stack Developer
        applicantId: normalUser.id,
        coverLetter:
          "I'm a Full Stack Developer with 4 years of experience in React and Node.js. I'm passionate about clean code and team collaboration.",
        resume: "https://resumes.jobsphere.com/john-doe.pdf",
        status: Status.PENDING,
      },
      {
        jobId: allJobs[0].id, // UI/UX Designer
        applicantId: normalUser?.id,
        coverLetter:
          "With 5 years in UX design, I specialize in intuitive interfaces and Figma prototyping. I'd love to help elevate your product design.",
        resume: "https://resumes.jobsphere.com/jane-smith.pdf",
        status: Status.SHORTLISTED,
      },
      {
        jobId: allJobs[5].id, // Project Manager
        applicantId: normalUser?.id,
        coverLetter:
          "Experienced PM with a track record of delivering large-scale projects under budget. Strong in Agile and communication.",
        resume: "https://resumes.jobsphere.com/alex-tan.pdf",
        status: Status.ACCEPTED,
      },
      {
        jobId: allJobs[5].id, // Digital Marketer
        applicantId: normalUser?.id,
        coverLetter:
          "I've led campaigns that increased traffic by 120%. My SEO and SEM skills would be an asset to your marketing team.",
        resume: "https://resumes.jobsphere.com/lisa-kim.pdf",
        status: Status.PENDING,
      },
      {
        jobId: allJobs[10].id, // Data Analyst
        applicantId: normalUser?.id,
        coverLetter:
          "Proficient in SQL, Python, and Power BI. I uncover data stories that drive decision-making and revenue growth.",
        resume: "https://resumes.jobsphere.com/rahul-singh.pdf",
        status: Status.REJECTED,
      },
      {
        jobId: allJobs[10].id,
        applicantId: normalUser?.id,
        coverLetter:
          "React, TypeScript, GraphQL — I’ve built scalable apps with all. I bring precision, speed, and collaboration to every team.",
        resume: "https://resumes.jobsphere.com/maria-gomez.pdf",
        status: Status.PENDING,
      },
      {
        jobId: allJobs[2].id,
        applicantId: normalUser?.id,
        coverLetter:
          "User empathy and minimalist design are my strengths. Let’s create experiences that convert and retain users.",
        resume: "https://resumes.jobsphere.com/emeka-obi.pdf",
        status: Status.REJECTED,
      },
      {
        jobId: allJobs[2].id,
        applicantId: normalUser?.id,
        coverLetter:
          "Certified Scrum Master with 6 years in SaaS. I excel at leading distributed teams and ensuring timely delivery.",
        resume: "https://resumes.jobsphere.com/hannah-lee.pdf",
        status: Status.ACCEPTED,
      },
      {
        jobId: allJobs[16].id,
        applicantId: normalUser?.id,
        coverLetter:
          "Growth hacking and email marketing are my thing. I've built lead funnels that boosted MRR by 40%.",
        resume: "https://resumes.jobsphere.com/thomas-brown.pdf",
        status: Status.SHORTLISTED,
      },
      {
        jobId: allJobs[16].id,
        applicantId: normalUser?.id,
        coverLetter:
          "Python, Pandas, Tableau — I deliver insights that speak business. Excited about data culture at your company.",
        resume: "https://resumes.jobsphere.com/susan-wang.pdf",
        status: Status.PENDING,
      },
      {
        jobId: allJobs[20].id,
        applicantId: normalUser?.id,
        coverLetter:
          "I've developed enterprise apps with microservices and CI/CD. Strong in Docker, Next.js, and performance optimization.",
        resume: "https://resumes.jobsphere.com/kevin-okafor.pdf",
        status: Status.SHORTLISTED,
      },
      {
        jobId: allJobs[25].id,
        applicantId: normalUser?.id,
        coverLetter:
          "From user research to prototyping, I bring the full UX cycle. Portfolio includes fintech and healthtech apps.",
        resume: "https://resumes.jobsphere.com/claire-nguyen.pdf",
        status: Status.PENDING,
      },
      {
        jobId: allJobs[27].id,
        applicantId: normalUser?.id,
        coverLetter:
          "Strong in stakeholder management and KPI reporting. I’ve led cross-functional teams across 3 continents.",
        resume: "https://resumes.jobsphere.com/daniel-mehta.pdf",
        status: Status.REJECTED,
      },
      {
        jobId: allJobs[25].id,
        applicantId: normalUser?.id,
        coverLetter:
          "I've scaled TikTok and Instagram accounts to 100k+. Creative strategy and content repurposing are my strengths.",
        resume: "https://resumes.jobsphere.com/natasha-mwamba.pdf",
        status: Status.ACCEPTED,
      },
      {
        jobId: allJobs[4].id,
        applicantId: normalUser?.id,
        coverLetter:
          "ETL pipelines, dashboarding, anomaly detection — I’ve done it all. I'm excited to join a data-forward company.",
        resume: "https://resumes.jobsphere.com/eric-lee.pdf",
        status: Status.PENDING,
      },
      {
        jobId: allJobs[4].id,
        applicantId: normalUser?.id,
        coverLetter:
          "I’ve worked on remote teams building Jamstack apps. I’m fast, reliable, and thrive in modern frontend ecosystems.",
        resume: "https://resumes.jobsphere.com/sophie-nalubega.pdf",
        status: Status.ACCEPTED,
      },
      {
        jobId: allJobs[1].id,
        applicantId: normalUser?.id,
        coverLetter:
          "I turn complexity into clarity. My mobile-first designs have improved onboarding and reduced churn.",
        resume: "https://resumes.jobsphere.com/robert-chan.pdf",
        status: Status.SHORTLISTED,
      },
      {
        jobId: allJobs[1].id,
        applicantId: normalUser?.id,
        coverLetter:
          "Strategic thinker with a technical background. I'm a PM who can talk to devs and business alike.",
        resume: "https://resumes.jobsphere.com/angela-owens.pdf",
        status: Status.PENDING,
      },
      {
        jobId: allJobs[8].id,
        applicantId: normalUser?.id,
        coverLetter:
          "I build brands that resonate. I've led global brand campaigns in 3 industries.",
        resume: "https://resumes.jobsphere.com/moses-adewale.pdf",
        status: Status.REJECTED,
      },
      {
        jobId: allJobs[8].id,
        applicantId: normalUser?.id,
        coverLetter:
          "Let’s turn raw data into gold. I specialize in A/B testing and product analytics.",
        resume: "https://resumes.jobsphere.com/sandra-white.pdf",
        status: Status.SHORTLISTED,
      },
    ];

    for (const application of applications) {
      await tx.application.create({
        data: application,
      });
    }
    console.log("applications created: ✅");

    console.log("Seeding completed....✅✅");
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
